project_id = "ywkrozcdrwbzojxxhuxu"

[functions.submit-contact]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.confirm-newsletter]
verify_jwt = false

[functions.send-admin-reply]
verify_jwt = true
