// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywkrozcdrwbzojxxhuxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3a3JvemNkcndiem9qeHhodXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNjQ5MjQsImV4cCI6MjA3NDk0MDkyNH0.p94P8truX3EL0Ri0hZmKBJSFbQ7qufuM6M890PyrxJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});