// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { ENV } from '@/config/env';
import type { Database } from './types';

const supabaseUrl = ENV.supabase.url;
const supabaseKey = ENV.supabase.publishableKey;

if (!supabaseUrl) {
  throw new Error(
    'Missing Supabase configuration: VITE_SUPABASE_URL is not defined.'
  );
}

if (!supabaseKey) {
  throw new Error(
    'Missing Supabase configuration: VITE_SUPABASE_PUBLISHABLE_KEY is not defined.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
